baseURL = "https://jackliusr.github.io"
languageCode = "en-us"
title = "My learning and diary"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
googleAnalytics = "UA-135021270-1"
disqusShortname = "jackliusr-gh"

enableRobotsTXT = true
env = "production"

[permalinks]
    posts = "/posts/:year/:month/:slug/"
    page = "/:slug/"
[params]
    show_reading_time = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[markup]
  [markup.asciidocExt]
preserveTOC = true

[menu]

[[menu.main]]
identifier = "about"
name = "About"
pre = "<i class='fa fa-heart'></i>"
url = "/about/"
weight = 110

[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<i class='fa fa-heart'></i>"
url = "/tags/"
weight = 90

[[menu.main]]
identifier = "categories"
name = "Categories"
pre = "<i class='fa fa-heart'></i>"
url = "/categories/"
weight = 80

[[menu.main]]
name = "Posts"
post = "<span class='alert'>New!</span>"
pre = "<i class='fa fa-road'></i>"
url = "/posts/"
weight = -100

[[menu.main]]
name = "Books"
post = "<span class='alert'>New!</span>"
pre = "<i class='fa fa-road'></i>"
url = "/readinglists/"
weight = 10

[[menu.main]]
name = "Notes"
post = "<span class='alert'>New!</span>"
pre = "<i class='fa fa-road'></i>"
url = "/notes/"
weight = -90
