---
title: "Install"
date: 2022-06-25T10:01:10+08:00
categories:
- tech
tags:
- jsonnet
- tanka
- jsonnet-bundler
- jsonnet-libs
---

In the past I knew jsonnet, however I didn't commit too much time to learn it until recently I encountered a data driven scenario, https://github.com/jackliusr/jsonnet-demo[generating istio yaml configurations based on an array of data]. The scenario is business driven, and I can foresee that there will be more data coming. What a waste of time to repeat the copy/paste procedures with little tweaks. I hated to do that. I figured out doing that data driven configuraton using jsonnet after spending half night yesterday.

The whole journey was not a smooth one. Here I logged my thoughts and hiccups I encountered.

At first, I wanted to use tanka.  I thought it might be too heavy after I learnt that there are environments and spec.json. I tried to use jsonnet-bundler to install jsonnet-libs following the https://tanka.dev/libraries/install-publish#install-a-library[document] and failed. I only got it right when I noticed the jb usage at https://tanka.dev/tutorial/k-lib#installation[here]. 

[source, bash]
----
# branch or tags are after @ symbol
jb install github.com/jsonnet-libs/k8s-libsonnet/1.21@main
----

After I successfully installed cert-manager-libsonnet using jb, I noticed that tanka supports more features than I thought. Considing the possibility to integrate tanka with argo-cd, I went back to use tanka again.

My final result is https://github.com/jackliusr/jsonnet-demo[here]. 

== References
* https://jsonnet.org/[jsonnet]
* https://github.com/jsonnet-libs[jsonnet-libs]
* https://tanka.dev/[tanka]
* https://github.com/jsonnet-bundler/jsonnet-bundler[jsonnet-bundler]