name: github pages

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          
      - name: build
        run: docker run --rm --volume $PWD:/src jackliusr/hugo-builder hugo

      - name: Publish Site
        uses: peaceiris/actions-gh-pages@v3  
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: master
          public_dir: ./public
